# Generated by Django 5.1.3 on 2024-12-01 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gas_booking', '0002_remove_user_id_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirm_password',
        ),
    ]
