# Generated by Django 5.1.3 on 2024-12-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_booking', '0003_remove_user_confirm_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='service_requests_files/')),
                ('service_type', models.CharField(choices=[('gas refill', 'Gas Refill'), ('gas fitting', 'Gas Fitting'), ('other', 'Other')], max_length=1000)),
                ('description', models.TextField()),
            ],
        ),
    ]
