# Generated by Django 5.1.3 on 2024-12-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_booking', '0004_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='username',
            field=models.CharField(default='Guest', max_length=15),
            preserve_default=False,
        ),
    ]
