# Generated by Django 5.1.3 on 2024-12-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_booking', '0005_services_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
